### ISSUE TITLE
k8s常用命令

### ISSUE THREAD

**Issue by AlfieriChou** [AlfieriChou/alfierichou.github.io#29]
1. 查看pods

```bash
kubectl get pods -n <namespace>
```

2. 以命令行方式进入pod

```bash
kubectl exec --namespace <namespace> -it <podName> -- /bin/sh
```

**Comment by AlfieriChou** [comment]
多集群配置

```
apiVersion: v1
clusters:
- cluster:
    server: https://192.168.10.190:6443
  name: cluster-1
- cluster:
    server: https://192.168.99.101:8443
  name: cluster-2
contexts:
- context:
    cluster: cluster-1
    user: kubernetes-admin-1
  name: cluster-1
- context:
    cluster: cluster-2
    user: kubernetes-admin-2
  name: cluster-2
current-context: cluster-2
kind: Config
preferences: {}
users:
- name: kubernetes-admin-1
  user:
    client-certificate: /home/user/.minikube/credential-for-cluster-1.crt
    client-key: /home/user/.minikube/credential-for-cluster-1.key
- name: kubernetes-admin-2
  user:
    client-certificate: /home/user/.minikube/credential-for-cluster-2.crt
    client-key: /home/user/.minikube/credential-for-cluster-2.key
```
